version: '3'
services:
  redis-node-0:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      - podium
    ports: 
      - "7000:6379"

  redis-node-1:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      - podium
    ports: 
      - "7001:6379"

  redis-node-2:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      - podium
    ports: 
      - "7002:6379"

  initialize-cluster:
    build:
      context: ../
      dockerfile: ./build/InitializeRedisClusterDockerfile
    image: initialize-redis-cluster:6.2.1-alpine
    environment:
      - "CLUSTER_HOSTS=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    networks:
      - podium

  redis-standalone:
    image: redis:6.2.1-alpine
    networks:
      - podium

  podium-cluster:
    build:
      context: ../
      dockerfile: ./build/RunAppDockerfile
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - initialize-cluster
    environment:
      - "PODIUM_REDIS_ADDRS=redis-node-0:6379"
      - "PODIUM_REDIS_CLUSTER_ENABLED=true"
    volumes:
      - "../:/podium"
      - "<<LOCAL_GO_MODCACHE>>:/go/pkg/mod"
    networks:
      - podium

  podium-test:
    build:
      context: ../
      dockerfile: ./build/TestAppDockerfile
    depends_on:
      - redis-standalone
    environment:
      - "PODIUM_REDIS_HOST=redis-standalone"
    volumes:
      - "../:/podium"
      - "<<LOCAL_GO_MODCACHE>>:/go/pkg/mod"
    networks:
      - podium

  podium-cluster-test:
    build:
      context: ../
      dockerfile: ./build/TestAppDockerfile
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    environment:
      - "PODIUM_REDIS_ADDRS=redis-node-0:6379"
      - "PODIUM_REDIS_CLUSTER_ENABLED=true"
    volumes:
      - "../:/podium"
      - "<<LOCAL_GO_MODCACHE>>:/go/pkg/mod"
    networks:
      - podium

networks:
  podium:
