[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.10.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/topfreegames/extensions"
  version = "8.0.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "~6.12.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.3.1"

[[override]]
  name = "golang.org/x/text"
  version = "0.3.2"

[[override]]
  name = "golang.org/x/sys"
  revision = "04f50cda93cbb67f2afa353c52f342100e80e625"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.20.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.9.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
