healthcheck:
  workingText: WORKING

redis:
  host: localhost
  port: 1212
  password: ""
  db: 0
  connectionTimeout: 200

api:
  maxReturnedMembers: 2000

newrelic:
  key: ""

worker:
  expirationCheckInterval: 5s
  expirationLimitPerRun: 1000
