healthcheck:
  workingText: WORKING

redis:
  host: localhost
  port: 1234
  connectionTimeout: 200

api:
  maxReturnedMembers: 2000

newrelic:
  key: ""

worker:
  expirationCheckInterval: 1s
  expirationLimitPerRun: 100
